# Generated by Django 5.2 on 2025-05-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
