# Generated by Django 5.2 on 2025-05-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_issue_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closing_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_issue', to='common.comment'),
        ),
    ]
