# Generated by Django 5.2 on 2025-05-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_issue_closing_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='common.repository'),
        ),
    ]
