# Generated by Django 5.2 on 2025-05-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_commit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='common.commit'),
        ),
    ]
